### ISSUE TITLE
[Other]: Suggestion

### ISSUE THREAD

**Issue by RobertoValente** [ixrzr/skills-icons#16]
### Description

What you think about adding a way to change the size of icons?

### Category

Feature Request

**Comment by ixrzr** [comment]
Hi @RobertoValente,

Thank you for suggesting the feature to add a way to dynamically resize the icons. I really appreciate your interest in improving the project!

After careful consideration, I’ve decided not to implement this feature **at this time**. Here’s the reasoning behind this decision:

### 1. Design Consistency
By keeping the icon size fixed within each perline configuration, the design remains predictable and uniform. This ensures that users can achieve consistent results across different use cases.

### 2. Scalability with Markdown and HTML
The API serves scalable SVGs, which means users can control their size directly in their embedding context:

In HTML, users can use the width and height attributes:

```html
<img src="https://skills-icons.vercel.app/api/icons?i=javascript,typescript" width="300" height="150" />
```

result:
<img src="https://skills-icons.vercel.app/api/icons?i=javascript,typescript" width="300" height="150" />

For Markdown (limited support), users can wrap the image in HTML tags:

```markdown
<img src="https://skills-icons.vercel.app/api/icons?i=express,mongodb" width="300" height="150">
```

result:
<img src="https://skills-icons.vercel.app/api/icons?i=express,mongodb" width="300" height="150">

### 3. API Simplicity
One of the core principles of the project is to keep the API lightweight and focused. Adding additional parameters for width and height could introduce unnecessary complexity.

I hope this explanation clarifies the reasoning behind this decision. Please let me know if you have further thoughts or ideas.

I always welcome contributions that enhance the API **while staying true to its core design philosophy**.

Thanks again!
