### ISSUE TITLE
[Documentation]: Add icon list

### ISSUE THREAD

**Issue by antoninoLorenzo** [ixrzr/skills-icons#8]
### Description

To provide better navigation a table like the one in [skill icons](https://github.com/tandpfun/skill-icons) could be provided in order to search for technologies by name.

Something like:
| Icon ID   | Icon                                                                                               |
|-----------|----------------------------------------------------------------------|
| `python` | <img src="https://skills-icons.vercel.app/api/icons?i=python"> |
```
| Icon ID | Icon |
|---------|------|
| `python` | <img src="https://skills-icons.vercel.app/api/icons?i=python"> |
```

I could help with it if needed.

### Category

Documentation

**Comment by ixrzr** [comment]
I'm working on automating the process so we won't need to update it manually every time a new icon is added.

**Comment by antoninoLorenzo** [comment]
> I'm working on automating the process so we won't need to update it manually every time a new icon is added.

I've now seen the workflow, the moment I opened the issue the table wasn't there but I guess that's done.
